### ISSUE TITLE
Podspec file does not validate

### ISSUE THREAD

**Issue by ronak2121** [CocoaLumberjack/CocoaLumberjack#729]
The podspec file does not validate (pod spec lint) on Cocoapods 1.0.0.rc1. It gives a bunch of errors.

**Comment by bpoplauschi** [comment]
pod spec lint
```
 -> CocoaLumberjack (2.3.0)
    - ERROR | public_header_files: The pattern includes header files that are not listedin source_files (/private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/CocoaLumberjack.h, /private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/DDAbstractDatabaseLogger.h, /private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/DDASLLogCapture.h, /private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/DDASLLogger.h, /private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/DDAssertMacros.h, /private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/DDFileLogger.h, /private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/DDLegacyMacros.h, /private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/DDLog+LOGV.h, /private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/DDLog.h, /private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/DDLogMacros.h, /private/var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/Pods/CocoaLumberjack/Classes/DDTTYLogger.h).
    - NOTE  | xcodebuild:  warning: hash mismatch: this object file was built against a different version of the module /Users/bogdan/Library/Developer/Xcode/DerivedData/ModuleCache/1DQPPKIMNRY7G/Foundation-1JOVK3AVN635O.pcm
    - ERROR | [CocoaLumberjack/Default, CocoaLumberjack/Core, CocoaLumberjack/CLI, and more...] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [CocoaLumberjack/Default] xcodebuild:  /Users/bogdan/Library/Developer/Xcode/DerivedData/App-cgxrdgwsrkgiikgacumuzwrbmzjg/Build/Products/Release-iphonesimulator/CocoaLumberjack/CocoaLumberjack.framework/Modules/module.modulemap:13:10: error: header 'DDContextFilterLogFormatter.h' not found
    - NOTE  | [CocoaLumberjack/Default, CocoaLumberjack/Core, CocoaLumberjack/CLI, and more...] xcodebuild:  /var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'CocoaLumberjack'
    - ERROR | [CocoaLumberjack/Default,CocoaLumberjack/CLI] xcodebuild:  /Users/bogdan/Library/Developer/Xcode/DerivedData/App-cgxrdgwsrkgiikgacumuzwrbmzjg/Build/Products/Release/CocoaLumberjack/CocoaLumberjack.framework/Modules/module.modulemap:13:10: error: header 'DDContextFilterLogFormatter.h' not found
    - ERROR | [watchOS] [CocoaLumberjack/Default] xcodebuild:  /Users/bogdan/Library/Developer/Xcode/DerivedData/App-cgxrdgwsrkgiikgacumuzwrbmzjg/Build/Products/Release-watchsimulator/CocoaLumberjack/CocoaLumberjack.framework/Modules/module.modulemap:13:10: error: header 'DDContextFilterLogFormatter.h' not found
    - NOTE  | [CocoaLumberjack/Default,CocoaLumberjack/Core] xcodebuild:  /var/folders/5l/14lp9tn5507_tvtnsbqdwhzr0000gn/T/CocoaPods/Lint/App/main.m:2:9: fatal error: could not build module 'CocoaLumberjack'
    - ERROR | [tvOS] [CocoaLumberjack/Default] xcodebuild:  /Users/bogdan/Library/Developer/Xcode/DerivedData/App-cgxrdgwsrkgiikgacumuzwrbmzjg/Build/Products/Release-appletvsimulator/CocoaLumberjack/CocoaLumberjack.framework/Modules/module.modulemap:13:10: error: header 'DDContextFilterLogFormatter.h' not found
    - ERROR | [CocoaLumberjack/Core] xcodebuild:  /Users/bogdan/Library/Developer/Xcode/DerivedData/App-cgxrdgwsrkgiikgacumuzwrbmzjg/Build/Products/Release-iphonesimulator/CocoaLumberjack/CocoaLumberjack.framework/Modules/module.modulemap:2:18: error: umbrella header 'CocoaLumberjack.h' not found
    - ERROR | [OSX] [CocoaLumberjack/Core] xcodebuild:  /Users/bogdan/Library/Developer/Xcode/DerivedData/App-cgxrdgwsrkgiikgacumuzwrbmzjg/Build/Products/Release/CocoaLumberjack/CocoaLumberjack.framework/Modules/module.modulemap:2:18: error: umbrella header 'CocoaLumberjack.h' not found
    - ERROR | [watchOS] [CocoaLumberjack/Core] xcodebuild:  /Users/bogdan/Library/Developer/Xcode/DerivedData/App-cgxrdgwsrkgiikgacumuzwrbmzjg/Build/Products/Release-watchsimulator/CocoaLumberjack/CocoaLumberjack.framework/Modules/module.modulemap:2:18: error: umbrella header 'CocoaLumberjack.h' not found
    - ERROR | [tvOS] [CocoaLumberjack/Core] xcodebuild:  /Users/bogdan/Library/Developer/Xcode/DerivedData/App-cgxrdgwsrkgiikgacumuzwrbmzjg/Build/Products/Release-appletvsimulator/CocoaLumberjack/CocoaLumberjack.framework/Modules/module.modulemap:2:18: error: umbrella header 'CocoaLumberjack.h' not found

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 10 errors.
```

**Comment by ronak2121** [comment]
Hi,

Do you have any idea when version 2.4.0 would be available?

Thanks

**Comment by bpoplauschi** [comment]
Hi there. Not sure. We just released 2.3.0 yesterday :)

**Comment by ronak2121** [comment]
I ask because of the issue above...it's scary when pod specs don't build properly...

**Comment by bpoplauschi** [comment]
The podspec was validated with the 0.39.0 version of CocoaPods. There must be something new in the 1.0.0 rc1 that breaks the build

**Comment by rivera-ernesto** [comment]
We should probably wait until 1.0.0 is released to avoid unnecessary modifications.

**Comment by sts2055** [comment]
Cocoapods version 1.0.0 has been released, but I'm still getting errors when linting:

`- ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:58:128: error: expected initial value after '='
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:58:214: error: expected ',' separator
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:70:138: error: expected initial value after '='
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:70:296: error: expected ',' separator
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:70:296: error: expected parameter type following ':'
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:72:2: error: expected ')' in parameter
    - NOTE  | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:70:23: note: to match this opening '('
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:74:137: error: expected initial value after '='
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:74:295: error: expected ',' separator
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:74:295: error: expected parameter type following ':'
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:76:2: error: expected ')' in parameter
    - NOTE  | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:74:22: note: to match this opening '('
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:78:137: error: expected initial value after '='
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:78:295: error: expected ',' separator
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:78:295: error: expected parameter type following ':'
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:80:2: error: expected ')' in parameter
    - NOTE  | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:78:22: note: to match this opening '('
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:82:140: error: expected initial value after '='
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:82:298: error: expected ',' separator
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:82:298: error: expected parameter type following ':'
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:84:2: error: expected ')' in parameter
    - NOTE  | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:82:25: note: to match this opening '('
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:86:138: error: expected initial value after '='
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:86:297: error: expected ',' separator
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:86:297: error: expected parameter type following ':'
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:88:2: error: expected ')' in parameter
    - NOTE  | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:86:23: note: to match this opening '('
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:93:54: error: expected initial value after '='
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:93:61: error: expected ',' separator
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:93:61: error: expected parameter type following ':'
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:70:13: error: expected '{' in body of function declaration
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:74:13: error: expected '{' in body of function declaration
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:78:13: error: expected '{' in body of function declaration
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:82:13: error: expected '{' in body of function declaration
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:86:13: error: expected '{' in body of function declaration
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:93:13: error: expected '{' in body of function declaration
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:59:92: error: use of unresolved identifier 'function'
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:59:108: error: use of unresolved identifier 'line'
    - ERROR | xcodebuild:  CocoaLumberjack/Classes/CocoaLumberjack.swift:59:119: error: use of unresolved identifier 'tag'`

**Comment by rivera-ernesto** [comment]
We have yet to try 1.0.0.

**Comment by bpoplauschi** [comment]
All the builds show this is not an issue. Will close it for now.
